version: '3.7'

services:
  pg:
    container_name: tn-samples-pg
    image: postgres:15-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./pg:/pg
    networks:
      - tbsamplenw
    environment:
      TZ: UTC
      POSTGRES_USER: taylor
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5435:5432

networks:
  tbsamplenw:
    name: tbsamplenw
